language: node_js
sudo: false
node_js:
  - '0.10.33'

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - 'npm install -g bower karma grunt-cli jshint'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages
